#include "ioP89LPC935.h"

PILHA   DEFINE  0x60
VARIA1  DEFINE  0X38
VARIA2  DEFINE  0X39
VARIA3  DEFINE  0X3A
        ASEG

        ORG 	0
	      JMP	INICIO		;INICIALIZA PERIFÉRICOS

	      ORG	0x03		;INTERRUPÇÃO EXTERNA 1
	      JMP	INTERRUPCAO
        ORG	0x80
INICIO
     	  MOV SP,#PILHA
        MOV   IEN0,#10000001b
        MOV   VARIA3,#03H
        MOV   VARIA2,#02H
        MOV   VARIA1,#01H

NORMAL  ;FUNCIONANDO EM MODO NORMAL(0 0)
        MOV   A,#04H
        ANL   PCON,#11111100b
LOOP1
        JMP   LOOP1   
        JMP   LOOP1
        
INTERRUPCAO
        DEC   A
IDLE    ;FUNCIONANDO EM MODO IDLE(0 1)
        CJNE  A,VARIA3,POWERDOWN
        ANL   PCON,#11111101b
        ORL   PCON,#00000001b
        JMP   IDLE

POWERDOWN ;FUNCIONANDO EM MODO POWERDOWN(1 0)
        CJNE  A,VARIA2,POWERDOWNTOTAL
        ANL   PCON,#11111110b
        ORL   PCON,#00000010b
        JMP   POWERDOWN
        
POWERDOWNTOTAL    ;FUNCIONANDO EM MODO POWERDOWN TOTAL(1 1)
        CJNE  A,VARIA1,NORMAL
        ORL   PCON,#00000011b
        JMP   POWERDOWNTOTAL
        
        RETI
        END
