#include "ioP89LPC935.h"
 
LED     DEFINE  P1.6
RELE    DEFINE  P0.0
BEEP    DEFINE  P2.7

CHAVES2 DEFINE  P1.4
CHAVES3 DEFINE  P2.0    ; IGUAL A LINHA 1 DOTECLADO
LDR     DEFINE  P0.2 ;DEFINE LABELS
RS      DEFINE  P0.1
E       DEFINE  P0.3
D1      DEFINE  P0.4
D2      DEFINE  P0.5
D3      DEFINE  P0.6
D4      DEFINE  P0.7
   
DADO_LCD    DEFINE  0x30        ;BYTE A SER ESCRITO NO LDC 4 BITS
NIBBLE_LCD  DEFINE  0x31        ;GUARDA NIBBLE A SER ESCRITO NO LCD 4 BITS
CONTADOR1   DEFINE  0x32        ;CONTADOR GENÉRICO
PILHA   DEFINE  0x60
     
ASEG

ORG     0
JMP     INICIO          ;INICIALIZA PERIFÉRICOS

ORG     0x03            ;INTERRUPÇÃO EXTERNA

JMP     TRATA_IE0
JMP     LOOP
  
ORG     0X13
JMP     TRATA_IE1
MP     LOOP

ORG     0x80
INICIO
MOV SP,#PILHA
CALL  BIOS              ;INICIALIZA PERIFERICOS

LOOP ;MODO POWER DOWN TOTAL  (1 1)
       
ORL     PCON,#03H
JMP     LOOP
  
TRATA_IE0
MOV     R1,#05H
CALL    L1_LCD
MOV     DPTR,#TAB1
CALL    STRING_LCD

PISCALED
CLR     LED
CALL    TEMPO500
SETB    LED
CALL    TEMPO500 
DJNZ    R1,PISCALED
CALL    LIMPA_LCD
RETI
      
TRATA_IE1
MOV     DPTR,#TAB2
CALL    L1_LCD
CALL    STRING_LCD
SETB    BEEP
CALL    TEMPO500
CALL    TEMPO500
CALL    LIMPA_LCD
RETI ;
SUBROTINAS

;INICIALIZAÇÃO IE1
MOV     IEN0,#10000101B ;IE1 -> 0X13 E IE0 -> 0X03    
                          
RET      
;FIM DA BIOS

;*** TABELAS
   
20204C45*TAB1: DB  '  LED ATIVADO   '
2042555A*TAB2: DB  ' BUZINA ATIVADA '
         
END
